### Get all boats (paginated)

GET http://localhost:8080/boats
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTk2NDA4MS00ZmJmLTc0N2EtYWU2NC1kMTcwMzBmYzNkY2MiLCJlbWFpbCI6Im92ZXN0b2VyaG9sdEBnbWFpbC5jb20iLCJuYW1lIjoiT3ZlIFN0w7hyaG9sdCIsInBpY3R1cmUiOm51bGwsInJvbGVzIjpbImFkbWluIl0sInBlcm1pc3Npb25zIjpbImFkbWluOndyaXRlIiwiYm9hdHM6cmVhZCJdLCJpYXQiOjE3NTI3NTIwNzYsImV4cCI6MTc1MjgzODQ3Nn0.t7GNPBahmXZlgZWKJeYLaOBa6SfjrlrKioNrCRwx63U

### Get boats with pagination parameters

GET http://localhost:8080/boats?page=1&limit=1
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTk2NDA4MS00ZmJmLTc0N2EtYWU2NC1kMTcwMzBmYzNkY2MiLCJlbWFpbCI6Im92ZXN0b2VyaG9sdEBnbWFpbC5jb20iLCJuYW1lIjoiT3ZlIFN0w7hyaG9sdCIsInBpY3R1cmUiOm51bGwsInJvbGVzIjpbImFkbWluIl0sInBlcm1pc3Npb25zIjpbImFkbWluOndyaXRlIiwiYm9hdHM6cmVhZCJdLCJpYXQiOjE3NTI3NTIwNzYsImV4cCI6MTc1MjgzODQ3Nn0.t7GNPBahmXZlgZWKJeYLaOBa6SfjrlrKioNrCRwx63U


### Get boats with owners with pagination parameters

GET http://localhost:8080/boats?page=1&limit=1&include=owners
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTk2NDA4MS00ZmJmLTc0N2EtYWU2NC1kMTcwMzBmYzNkY2MiLCJlbWFpbCI6Im92ZXN0b2VyaG9sdEBnbWFpbC5jb20iLCJuYW1lIjoiT3ZlIFN0w7hyaG9sdCIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NMbnptSWs1LWIzbUVkWXdhTjFUdWZnSV9xZk5Nc213cUpEVDZnTGdsWk9DX3o5WUdyOVJBPXM5Ni1jIiwicm9sZXMiOlsiYWRtaW4iXSwicGVybWlzc2lvbnMiOlsiY291bnRyaWVzOnJlYWQiLCJ1c2VyczpyZWFkX293biIsInVzZXJzOnJlYWQiLCJib2F0czpkZWxldGUiLCJ1c2Vyczp3cml0ZV9vd24iLCJjb3VudHJpZXM6d3JpdGUiLCJib2F0czp3cml0ZSIsImNvdW50cmllczpkZWxldGUiLCJ1c2Vyczp3cml0ZSIsImJvYXRzOnJlYWQiLCJ1c2VyczpkZWxldGUiXSwiaWF0IjoxNzUzNDQyNzkxLCJleHAiOjE3NTM1MjkxOTF9.GLDwbzhpwTCOK4MGM2Pv7BiraR__NdTp6_BVAkSSMUU

### Create new boat

POST http://localhost:8080/boats
Content-Type: application/json

{
    "name": "First Time",
    "brand": "First",
    "model": "Class 8",
    "sailNumber": "NOR5828",
    "countryId": "0196407f-574a-7061-a353-03f612af0766"
}

### Create new boat - bad data

POST http://localhost:8080/boats
Content-Type: application/json

{
    "name": "H",
    "brand": "",
    "model": "C",
    "sailNumber": "AB8-12",
    "countryId": "0196407f-574a-7061-a353-03f612af0766"
}


### Update boat (PUT)
PUT http://localhost:8080/boats/01964081-4fbf-747a-ae64-d17030fc3dcc
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTk2NDA4MS00ZmJmLTc0N2EtYWU2NC1kMTcwMzBmYzNkY2MiLCJlbWFpbCI6Im92ZXN0b2VyaG9sdEBnbWFpbC5jb20iLCJuYW1lIjoiT3ZlIFN0w7hyaG9sdCIsInBpY3R1cmUiOm51bGwsInJvbGVzIjpbImFkbWluIl0sInBlcm1pc3Npb25zIjpbImFkbWluOndyaXRlIiwiYm9hdHM6cmVhZCJdLCJpYXQiOjE3NTI3NTIwNzYsImV4cCI6MTc1MjgzODQ3Nn0.t7GNPBahmXZlgZWKJeYLaOBa6SfjrlrKioNrCRwx63U
Content-Type: application/json

{
    "name": "Updated Boat Name",
    "brand": "Updated Brand",
    "model": "Updated Model",
    "sailNumber": "NOR9999",
    "countryId": "0196407f-574a-7061-a353-03f612af0766"
}

### Delete boat (DELETE)
DELETE http://localhost:8080/boats/01964081-4fbf-747a-ae64-d17030fc3dcc
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTk2NDA4MS00ZmJmLTc0N2EtYWU2NC1kMTcwMzBmYzNkY2MiLCJlbWFpbCI6Im92ZXN0b2VyaG9sdEBnbWFpbC5jb20iLCJuYW1lIjoiT3ZlIFN0w7hyaG9sdCIsInBpY3R1cmUiOm51bGwsInJvbGVzIjpbImFkbWluIl0sInBlcm1pc3Npb25zIjpbImFkbWluOndyaXRlIiwiYm9hdHM6cmVhZCJdLCJpYXQiOjE3NTI3NTIwNzYsImV4cCI6MTc1MjgzODQ3Nn0.t7GNPBahmXZlgZWKJeYLaOBa6SfjrlrKioNrCRwx63U


### Add owner to boat
@addOwnerToBoat_boatId=01969ebb-a363-78c3-a7cc-1452936b991b
@addOwnerToBoat_userId=01964081-4fbf-747a-ae64-d17030fc3dcc
POST http://localhost:8080/boats/{{addOwnerToBoat_boatId}}/owners/{{addOwnerToBoat_userId}}
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiIwMTk2NDA4MS00ZmJmLTc0N2EtYWU2NC1kMTcwMzBmYzNkY2MiLCJlbWFpbCI6Im92ZXN0b2VyaG9sdEBnbWFpbC5jb20iLCJuYW1lIjoiT3ZlIFN0w7hyaG9sdCIsInBpY3R1cmUiOiJodHRwczovL2xoMy5nb29nbGV1c2VyY29udGVudC5jb20vYS9BQ2c4b2NMbnptSWs1LWIzbUVkWXdhTjFUdWZnSV9xZk5Nc213cUpEVDZnTGdsWk9DX3o5WUdyOVJBPXM5Ni1jIiwicm9sZXMiOlsiYWRtaW4iXSwicGVybWlzc2lvbnMiOlsiY291bnRyaWVzOnJlYWQiLCJ1c2VyczpyZWFkX293biIsInVzZXJzOnJlYWQiLCJib2F0czpkZWxldGUiLCJ1c2Vyczp3cml0ZV9vd24iLCJjb3VudHJpZXM6d3JpdGUiLCJib2F0czp3cml0ZSIsImNvdW50cmllczpkZWxldGUiLCJ1c2Vyczp3cml0ZSIsImJvYXRzOnJlYWQiLCJ1c2VyczpkZWxldGUiXSwiaWF0IjoxNzUzNDMxMTk5LCJleHAiOjE3NTM1MTc1OTl9.fK1tXBzVeOd5tJ0U2Q9MFySMRd5N8M-aCygwjSBhCW0