### Getting all countries
GET http://localhost:8080/countries

### Getting country by ID
@country_id=019657a2-2a26-74d0-9c7d-fa91f8be1054
GET http://localhost:8080/countries/{{country_id}}

### Getting country by ID which does not exist
@country_id_does_not_exist=01965c2f-70e0-7c28-939b-c9993755566a
GET http://localhost:8080/countries/{{country_id_does_not_exist}}

### Getting country by iso code
@country_iso_code=nor
GET http://localhost:8080/countries/code/{{country_iso_code}}


### Getting country by iso code - when code does not exist
@bad_country_iso_code=xyz
GET http://localhost:8080/countries/code/{{bad_country_iso_code}}

### Getting country by iso code - when format is incorrect
@wrong_format_country_iso_code=xyzabc
GET http://localhost:8080/countries/code/{{wrong_format_country_iso_code}}


### Insert country
POST http://localhost:8080/countries
Content-Type: application/json

{
  "iso_name" : "Germany",
  "iso_alpha_2" : "DE",
  "iso_alpha_3" : "DEU"
}

### Insert country - incorrect length on iso_alpha_2 and iso_alpha_3. Validation error
POST http://localhost:8080/countries
Content-Type: application/json

{
  "iso_name" : "Fakeland",
  "iso_alpha_2" : "F",
  "iso_alpha_3" : "Fake"
}

### Delete country by ID
@delete_country_id = 0196407f-574a-7061-a353-03f612af0766
DELETE http://localhost:8080/countries/{{delete_country_id}}


### Update country
@update_country_id=019657a2-2a26-74d0-9c7d-fa91f8be1054
PUT http://localhost:8080/countries/{{update_country_id}}
Content-Type: application/json

{
  "iso_name" : "Finlandia",
  "iso_alpha_2" : "FI",
  "iso_alpha_3" : "FIN"
}
