### Getting all countries
GET http://localhost:8080/countries

### Getting country by ID
@country_id=019657a2-2a26-74d0-9c7d-fa91f8be1054
GET http://localhost:8080/countries/{{country_id}}

### Getting country by ID which does not exist
@country_id_does_not_exist=01965c2f-70e0-7c28-939b-c9993755566a
GET http://localhost:8080/countries/{{country_id_does_not_exist}}

### Getting country by iso code
@country_iso_code=nor
GET http://localhost:8080/countries/code/{{country_iso_code}}


### Getting country by iso code - when code does not exist
@bad_country_iso_code=xyz
GET http://localhost:8080/countries/code/{{bad_country_iso_code}}

### Getting country by iso code - when format is incorrect
@wrong_format_country_iso_code=xyzabc
GET http://localhost:8080/countries/code/{{wrong_format_country_iso_code}}


### Insert country
POST http://localhost:8080/countries
Content-Type: application/json

{
  "isoName" : "Finland",
  "isoAlpha2" : "FI",
  "isoAlpha3" : "FIN"
}

### Insert country - incorrect length on iso_alpha_2 and iso_alpha_3. Validation error
POST http://localhost:8080/countries
Content-Type: application/json

{
  "isoName" : "Fakeland",
  "isoAlpha2" : "F",
  "isoAlpha3" : "Fake"
}

### Delete country by ID
@delete_country_id = 019677b0-f56b-7ec1-986a-6845e971df1b
DELETE http://localhost:8080/countries/{{delete_country_id}}


### Update country
@update_country_id=01967b4c-8a93-792b-9865-b2a4a5365fe0
PUT http://localhost:8080/countries/{{update_country_id}}
Content-Type: application/json

{
  "isoName" : "Finland",
  "isoAlpha2" : "FI",
  "isoAlpha3" : "FIN"
}


### Update country - incorrect length on iso_alpha_2 and iso_alpha_3. Validation error
@incorrect_update_country_id=01967b4c-8a93-792b-9865-b2a4a5365fe0
PUT http://localhost:8080/countries/{{incorrect_update_country_id}}
Content-Type: application/json

{
  "isoName" : "Finlandia",
  "isoAlpha2" : "FINN",
  "isoAlpha3" : "FI"
}
