### Getting all countries
GET http://localhost:8080/countries

### Getting country by ID
@country_id=ddba3f2c-3c65-47e6-a15b-ae9a246e8fad
GET http://localhost:8080/countries/{{country_id}}

### Insert country
POST http://localhost:8080/countries
Content-Type: application/json

{
  "iso_name" : "Finland",
  "iso_alpha_2" : "FI",
  "iso_alpha_3" : "FIN"
}

### Delete country by ID
@delete_country_id = 0196407f-574a-7061-a353-03f612af0766
DELETE http://localhost:8080/countries/{{delete_country_id}}