
### Getting all users
GET http://localhost:8080/users

### Getting user by ID
@user_id = 01964081-4fbf-747a-ae64-d17030fc3dcc
GET http://localhost:8080/users/{{user_id}}



### Create new user

POST http://localhost:8080/users
Content-Type: application/json

{
    "first_name": "Martin",
    "last_name": "Størholt",
    "email": "martinstoerholt@gmail.com",
    "phone": "47032900",
    "country_id": "0196407f-574a-7061-a353-03f612af0766"
}


### Get all users
GET http://localhost:8080/users

### Delete user by ID
@delete_user_id = 01964081-4fbf-747a-ae64-d17030fc3dcc
DELETE http://localhost:8080/users/{{delete_user_id}}