
### Getting all users
GET http://localhost:8080/users



### Create new user

POST http://localhost:8080/users
Content-Type: application/json

{
    "first_name": "Ove",
    "last_name": "Størholt",
    "email": "ovestoerholt@gmail.com",
    "phone": "93021759",
    "country_id": "ddba3f2c-3c65-47e6-a15b-ae9a246e8fad"
}
