
### Getting all users
GET http://localhost:8080/users



### Create new user

POST http://localhost:8080/users
Content-Type: application/json

{
    "first_name": "Martin",
    "last_name": "Størholt",
    "email": "martinstoerholt@gmail.com",
    "phone": "47032900",
    "country_id": "ddba3f2c-3c65-47e6-a15b-ae9a246e8fad"
}


### Get all users
GET http://localhost:8080/users